# Generated by Django 5.2.12 on 2026-03-13 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='trees/')),
                ('planted_at', models.DateTimeField(auto_now_add=True)),
                ('carbon_offset', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('planted', 'Planted')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
